version: '3'

services:
  web:
    build: ./thyme
    ports:
      - "5000:5000"
    volumes:
      - ./thyme:/code
    depends_on:
      - postgres
    restart: always
    command: bash -c "/usr/wait-for-it.sh --timeout=0 postgres:5432 && alembic upgrade head && python manage_web.py"
    environment:
      DATABASE_URL: "postgresql://postgres:pass@postgres:5432/thyme"
      DEBUG: "True"

  api:
    build: ./thyme
    ports:
      - "6000:6000"
    volumes:
      - ./thyme:/code
    depends_on:
      - postgres
    restart: always
    command: bash -c "/usr/wait-for-it.sh --timeout=0 postgres:5432 && alembic upgrade head && uvicorn manage_api:app --reload"
    environment:
      DATABASE_URL: "postgresql://postgres:pass@postgres:5432/thyme"
      DEBUG: "True"

  postgres:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: thyme
