version: '3'

services:
  web:
    build: ./thyme
    ports:
      - "5000:5000"
    volumes:
      - ./thyme:/code
    command: python manage_web.py
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: thyme
