version: '3'

services:
  web:
    build: ./thyme
    ports:
      - "5000:5000"
    volumes:
      - ./thyme:/code
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:pass@postgres:5432/thyme"
      DEBUG: "True"
      NEWS_API_KEY: "${NEWS_API_KEY}"

  postgres:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: thyme
