"""Add tasks

Revision ID: 20200927101620
Revises: 
Create Date: 2020-09-27 10:16:21.684266

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20200927101620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('created', 'done', 'decline', name='statuses'), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
